# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acit/bq_table.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x63it/bq_table.proto\x12\rgen_bq_schema\x1a google/protobuf/descriptor.proto\"Z\n\x16\x42igQueryMessageOptions\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x16\n\x0euse_json_names\x18\x02 \x01(\x08\x12\x14\n\x0c\x65xtra_fields\x18\x03 \x03(\t:^\n\rbigquery_opts\x12\x1f.google.protobuf.MessageOptions\x18\xfd\x07 \x01(\x0b\x32%.gen_bq_schema.BigQueryMessageOptionsB<Z:github.com/GoogleCloudPlatform/protoc-gen-bq-schema/protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acit.bq_table_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(bigquery_opts)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/GoogleCloudPlatform/protoc-gen-bq-schema/protos'
  _BIGQUERYMESSAGEOPTIONS._serialized_start=72
  _BIGQUERYMESSAGEOPTIONS._serialized_end=162
# @@protoc_insertion_point(module_scope)
